import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <main className="flex-1">{children}</main>

        <footer className="flex items-center justify-center w-full max-w-4xl mt-8">
          <p className="text-xs text-center text-gray-500">
            © Illustrations designed by Felix Wong and under CC0 license
          </p>
        </footer>
      </body>
    </html>
  );
}
